site_name: Sriram Developer Setup
nav:
  - Home:
      - Home: index.md
  - Legend:
      - Symbols Help: legend.md
  - Complete Setup:
      - MacBook Instructions:
          - Macbook Initial Setup: macbook/initial-setup.md
          - RayCast & Karabiner: 
              - MacBook RayCast & Karabiner Setup: macbook/RayCast and Karabiner/raycast.md
              - MacBook RayCast & Karabiner Keyboard Shortcuts: macbook/RayCast and Karabiner/keyboard-shortcuts.md
          - Terminal:
              - MacBook NeoVim Setup: macbook/Terminal/neovim-setup.md
              - MacBook TMUX Setup: macbook/Terminal/tmux-setup.md
              - MacBook Terminal Keyboard Shortcuts: macbook/Terminal/keyboard-shortcuts.md
          - Visual Studio Code:
              - MacBook VSCode Setup: macbook/Visual Studio Code/vscode-setup.md
              - MacBook VSCode Extensions List: macbook/Visual Studio Code/extensions.md
              - MacBook VSCode Keyboard Shortcuts: macbook/Visual Studio Code/keyboard-shortcuts.md
              - MacBook VSCode Settings JSON: macbook/Visual Studio Code/settings.md
              - MacBook VSCode Keybindings JSON: macbook/Visual Studio Code/keybindings.md
              - MacBook VSCode Themes & Icons: macbook/Visual Studio Code/themes.md
              - MacBook VSCode User Snippets: macbook/Visual Studio Code/user_snippets.md
              - MacBook VSCode Customise Layout: macbook/Visual Studio Code/customise-layout.md
          - Cursor:
              - MacBook Cursor Setup: macbook/Cursor/cursor-setup.md
              - MacBook Cursor Extensions List: macbook/Cursor/extensions.md
              - MacBook Cursor Keyboard Shortcuts: macbook/Cursor/keyboard-shortcuts.md
              - MacBook Cursor Settings JSON: macbook/Cursor/settings.md
              - MacBook Cursor Keybindings JSON: macbook/Cursor/keybindings.md
              - MacBook Cursor Themes & Icons: macbook/Cursor/themes.md
              - MacBook Cursor User Snippets: macbook/Cursor/user_snippets.md
  - Daily Keyboard Shortcuts:
      - MacBook RayCast & Karabiner Keyboard Shortcuts: daily_shortcuts/raycast.md
      - MacBook Terminal Keyboard Shortcuts: daily_shortcuts/terminal.md
      - MacBook VSCode Keyboard Shortcuts: daily_shortcuts/vscode.md
      - MacBook Cursor Keyboard Shortcuts: daily_shortcuts/cursor.md
theme: readthedocs
